# TestUser Token : 4b167d854fb9577405caf997a68ea34767eaa6ff
# TestUser1 Token : 4a225ba57e6672179c3e9c2e2c1e722d8da8221c	
# admin Token : 750b3bcfab29f403a07ae4ac13dd50cdeed3080c	

# Create Comment
POST http://127.0.0.1:8000/api/comments/
Content-Type: application/json
Authorization: Token 4a225ba57e6672179c3e9c2e2c1e722d8da8221c

{"content":"Nice comment", "post":"1"}

### 
# delete comment by self
DELETE http://127.0.0.1:8000/api/comments/5/
Content-Type: application/json
Authorization: Token 4a225ba57e6672179c3e9c2e2c1e722d8da8221c

{}

### 
# delete comments by admin
DELETE http://127.0.0.1:8000/api/comments/5/
Content-Type: application/json
Authorization: Token 750b3bcfab29f403a07ae4ac13dd50cdeed3080c

{}

###
# get comment details by anyone (no Auth) 
GET http://127.0.0.1:8000/api/comments/3/
Content-Type: application/json
#Authorization: Token 4b167d854fb9577405caf997a68ea34767eaa6ff

{}
###

# get comment details by admin 
GET http://127.0.0.1:8000/api/comments/3/
Content-Type: application/json
Authorization: Token 750b3bcfab29f403a07ae4ac13dd50cdeed3080c

{}
###
# get comment list details by admin 
GET http://127.0.0.1:8000/api/comments/
Content-Type: application/json
Authorization: Token 750b3bcfab29f403a07ae4ac13dd50cdeed3080c

{}

###

# Test to update author title by the user themselves (specific user)
# should not change because field is read only
PATCH http://127.0.0.1:8000/api/comments/3/
Content-Type: application/json
Authorization: Token 4a225ba57e6672179c3e9c2e2c1e722d8da8221c

{"author": "8"}

###
# Test to update post by the any user
# should fail no permission
PATCH http://127.0.0.1:8000/api/comments/3/
Content-Type: application/json
Authorization: Token 4b167d854fb9577405caf997a68ea34767eaa6ff

{"post": "10"}


#########
# Test to update content by the any user
# should fail no permission
PATCH http://127.0.0.1:8000/api/comments/3/
Content-Type: application/json
Authorization: Token 4b167d854fb9577405caf997a68ea34767eaa6ff

{"content": "Normal user updated the content"}
###

#  Test to update content by admin
PATCH http://127.0.0.1:8000/api/comments/3/
Content-Type: application/json
Authorization: Token 750b3bcfab29f403a07ae4ac13dd50cdeed3080c

{"content": "content updated by admin"}

###
# update all serialized fields by admin
PUT http://127.0.0.1:8000/api/comments/3/
Content-Type: application/json
Authorization: Token 750b3bcfab29f403a07ae4ac13dd50cdeed3080c

{  "id": "5","content": "content updated by admin with put","author":"1","post":"9"}

###
# update all serialized fields by user
PUT http://127.0.0.1:8000/api/comments/3/
Content-Type: application/json
Authorization: Token 4a225ba57e6672179c3e9c2e2c1e722d8da8221c

{  "id": "5","content": "content updated by user with put","author":"1","post":"9"}

###
